### ISSUE TITLE
ticking entity issue

### ISSUE THREAD

**Issue by jitterdev** [diamonddevv/enderism#7]
```
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1309.method_5998(net.minecraft.class_1268)" because "source" is null
        at net.minecraft.class_1309.handler$dfg000$enderism$applyCharmEffect(class_1309.java:28313) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_5643(class_1309.java) ~[server-intermediary.jar:?]
        at net.minecraft.class_1671.method_7475(class_1671.java:244) ~[server-intermediary.jar:?]
        at net.minecraft.class_1671.method_16830(class_1671.java:178) ~[server-intermediary.jar:?]
        at net.minecraft.class_1671.method_5773(class_1671.java:171) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218.method_18762(class_3218.java:739) ~[server-intermediary.jar:?]
        at net.minecraft.class_1937.mixinextras$bridge$accept$216(class_1937.java) ~[server-intermediary.jar:?]
        at com.bawnorton.neruina.handler.NeruinaTickHandler.safelyTickEntities$notTheCauseOfTickLag(NeruinaTickHandler.java:115) ~[neruina-1.3.0-fabric+1.18.2-1.20.1.jar:?]
        at net.minecraft.class_1937.wrapOperation$fmp000$neruina$catchTickingEntities(class_1937.java:17048) ~[server-intermediary.jar:?]
        at net.minecraft.class_1937.method_18472(class_1937.java:480) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218.method_31420(class_3218.java:385) ~[server-intermediary.jar:?]
        at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218.method_18765(class_3218.java:353) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.handler$bkl000$carpet$modifiedRunLoop(MinecraftServer.java:20942) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by diamonddevv** [comment]
hello! could you please specify which version of enderism you were using at the time?
